# Generated by Django 3.2.7 on 2021-09-23 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPlan',
            new_name='UserPlans',
        ),
    ]
